steps:
  - block: "🛤 Configure Parallel Jobs"
    fields:
      - select: Jobs to Generate
        hint: |
          A large number of jobs will decrease the performance of this page! Be careful!
        key: job-count
        default: 50
        options:
          - label: "5 Jobs"
            value: 5
          - label: "10 Jobs"
            value: 10
          - label: "50 Jobs"
            value: 50
          - label: "100 Jobs"
            value: 100
          - label: "150 Jobs"
            value: 150
          - label: "200 Jobs (Heaps!)"
            value: 200
          - label: "250 Jobs (Wow!)"
            value: 250
          - label: "500 Jobs (Careful!)"
            value: 500

      - select: Job Duration
        hint: |
          Each job will wait this long before exiting.
          Beware, if you have few agents, a large number of jobs and a long duration, 
          the pipeline will take a long time!
        key: job-duration
        default: 5
        options:
          - label: "None"
            value: 0
          - label: "1 Second"
            value: 1
          - label: "5 Seconds"
            value: 5
          - label: "10 Seconds"
            value: 10
          - label: "30 Seconds"
            value: 30
          - label: "1 Minute"
            value: 60
          - label: "5 Minutes"
            value: 300
          - label: "10 Minutes"
            value: 600
          - label: "30 Minutes"
            value: 1800
          - label: "1 Hour"
            value: 3600

  - label: ":pipeline:"
    command: |
      bash <<SCRIPT
        set -euo pipefail

        TESTER_JOB_DURATION=$(buildkite-agent meta-data get job-duration)
        TESTER_JOB_COUNT=$(buildkite-agent meta-data get job-count)

        buildkite-agent pipeline upload <<PIPELINEYAML
          steps:
            - command: "sleep \\\$TESTER_JOB_DURATION"
              label: "Job %n"
              parallelism: \\\$TESTER_JOB_COUNT
        PIPELINEYAML
      SCRIPT
